apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: evershop-production
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/MariemSaiidii/evershop-gitops.git
    targetRevision: HEAD
    path: evershop-chart
    helm:
      valueFiles:
        - ../environments/production/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
