# EverShop app related values
evershop:
  replicaCount: 1                    # Number of EverShop pods
  image:
    repository: evershop/evershop   # Docker image repo for EverShop app
    tag: latest                     # Image tag/version
  containerPort: 3000               # Port EverShop listens to in container
  nodePort: 30002                   # External port exposed on NodePort service
     
# PostgreSQL DB related values
postgres:
  serviceName: postgres             # Service name to connect to DB from app
  database:
      host: postgres  
  port: 5432                       # Default PostgreSQL port
  user: postgres                   # DB username
  password: postgres               # DB password (for demo/dev only)
  replicaCount: 1                  # Number of DB pods (usually 1)
  image:
    repository: postgres            # PostgreSQL image repo
    tag: "16"                      # PostgreSQL version tag

# Global image pull policy for containers (optional, default can be 'IfNotPresent')
imagePullPolicy: IfNotPresent

# Other general Helm chart config options (unused now, but keep for future)
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

livenessProbe:
  httpGet:
    path: /
    port: http

readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []
volumeMounts: []

nodeSelector: {}
tolerations: []
affinity: {}
